// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"back/api/controller"
	"back/api/router"
	"back/common/middleware"
	"back/dal/dao"
	"back/logic/appService"
	"back/logic/domainService"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp() *gin.Engine {
	query := dao.DBMaster()
	questionDomainService := domainService.NewQuestionDomainServiceV1(query)
	questionAppService := appService.NewQuestionAppServiceV1(questionDomainService)
	questionController := controller.NewQuestionController(questionAppService)
	v := middleware.GetHandlerFunc()
	engine := router.RegisterRoutersAndMiddleware(questionController, v...)
	return engine
}
