// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"back/api/controller"
	"back/api/router"
	"back/common/middleware"
	"back/dal/dao"
	"back/logic/repository"
	"back/logic/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp() *gin.Engine {
	query := dao.DBMaster()
	questionRepository := repository.NewQuestionRepositoryV1(query)
	questionService := service.NewQuestionServiceV1(questionRepository)
	questionController := controller.NewQuestionController(questionService)
	userRepository := repository.NewUserRepositoryV1(query)
	userService := service.NewUserServiceV1(userRepository)
	userController := controller.NewUserController(userService)
	v := middleware.GetHandlerFunc()
	engine := router.RegisterRoutersAndMiddleware(questionController, userController, v...)
	return engine
}
