app:
  env: "dev"
  name: "oj"
  log:
    path: "./log/oj.log"
    maxSize: 100
    maxAge: 60
  pagination:
    defaultSize: 20
    maxSize: 100
  port: 8080
database:
  master:
    type: "mysql"
    dsn: "%s:%s@tcp(%s:3306)/oj?charset=utf8mb4&parseTime=True&loc=Local"
    maxOpen: 100
    maxIdle: 10
    maxLifeTime: 60
  slave:
    type: "mysql"
    dsn: "%s:%s@tcp(%s:3306)/oj?charset=utf8mb4&parseTime=True&loc=Local"
    maxOpen: 100
    maxIdle: 10
    maxLifeTime: 60